# Generated by Django 3.2.4 on 2021-09-21 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='process name')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time process start')),
                ('status', models.CharField(max_length=10, verbose_name='process status')),
                ('QT', models.CharField(max_length=100, verbose_name='query sets')),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taskid', models.IntegerField()),
            ],
        ),
    ]
